import type { PRReview } from "@/lib/schemas";

export function reviewToMarkdown(review: PRReview, prUrl: string): string {
  const EMOJI = { approve: "✅", request_changes: "❌", needs_info: "❓" };
  const lines: string[] = [
    `# PR Review`,
    `> ${prUrl}`,
    ``,
    `## Verdict: ${EMOJI[review.verdict]} ${review.verdict.replace("_", " ")}`,
    ``,
    `## Summary`,
    review.summary,
    ``,
  ];

  if (review.positives.length) {
    lines.push(`## What's good`, ...review.positives.map(p => `- ✓ ${p}`), ``);
  }

  const bySeverity = ["critical", "warning", "suggestion", "praise"] as const;
  for (const sev of bySeverity) {
    const group = review.comments.filter(c => c.severity === sev);
    if (!group.length) continue;
    lines.push(`## ${sev.charAt(0).toUpperCase() + sev.slice(1)} (${group.length})`);
    for (const c of group) {
      lines.push(`\n**\`${c.file}${c.line ? `:${c.line}` : ""}\`**`);
      lines.push(c.message);
    }
    lines.push(``);
  }

  lines.push(`---`, `*Generated by PR Review Agent*`);
  return lines.join("\n");
}

export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function copyToClipboard(text: string) {
  return navigator.clipboard.writeText(text);
}